# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d2934fbef80ceac89ed5c3555b3f18f60ead682a9ecfc558a308c43b9fcdd61bb6f1ed81c09d868a1bb69afc6477602342bfd64d305fee9dd0773c68a288d03

test:
  secret_key_base: ee852083e4e9665812f25cf6eac14262f6af0800a47e87a44f86caa8109add27545b7c6acc710012a3c0aba2e3f551cd67339cfa55ef46e65857c930c8b348c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
